// Generated by CoffeeScript 1.7.1
var FrontendController, Model,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

FrontendController = require('./base/frontend').FrontendController;

Model = require('../../core/models').Model;

exports.MainPageController = (function(_super) {
  __extends(MainPageController, _super);

  function MainPageController() {
    this.index = __bind(this.index, this);
    MainPageController.__super__.constructor.apply(this, arguments);
  }

  MainPageController.preprocessRequest = function(req, res, next) {
    return MainPageController.__super__.constructor.preprocessRequest.apply(this, arguments);
  };

  MainPageController.prototype.index = function(req, res) {
    var viewName;
    viewName = this._getViewName();
    this._assets.css.addFile("font-awesome");
    this._assets.js.addFile("auction");
    this._assets.js.addFile("" + viewName);
    this._assets.compile();
    return Model.instanceOf('auction').findAll().then((function(_this) {
      return function(auctions) {
        var userPromise;
        userPromise = _this.get('userPromise');
        if (userPromise) {
          return userPromise.then(function(user) {
            return res.render(viewName, {
              title: 'Auctions home',
              jsTags: _this._assets.renderJs(),
              cssTags: _this._assets.renderCss(),
              auctions: auctions,
              getSecsDiffToDate: getSecsDiffToDate,
              configs: configs.getFrontendConfigs(),
              user: user
            });
          }).fail(function(e) {
            return console.log(e.toJson());
          });
        } else {
          return res.render(viewName, {
            title: 'Auctions home',
            jsTags: _this._assets.renderJs(),
            cssTags: _this._assets.renderCss(),
            auctions: auctions,
            getSecsDiffToDate: getSecsDiffToDate,
            configs: configs.getFrontendConfigs(),
            user: null
          });
        }
      };
    })(this)).fail(function(e) {
      return console.log(e.toJson());
    });
  };

  return MainPageController;

})(FrontendController);
