// Generated by CoffeeScript 1.7.1
var FrontendController,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

FrontendController = require('./base/frontend').FrontendController;

exports.MainPageController = (function(_super) {
  __extends(MainPageController, _super);

  function MainPageController() {
    this.index = __bind(this.index, this);
    MainPageController.__super__.constructor.apply(this, arguments);
  }

  MainPageController.preprocessRequest = function(req, res, next) {
    return MainPageController.__super__.constructor.preprocessRequest.apply(this, arguments);
  };

  MainPageController.prototype.index = function(req, res) {
    return res.render(this._getViewName(), {
      jsTags: this._assets.js.renderTags(),
      cssTags: this._assets.css.renderTags()
    });
  };

  return MainPageController;

})(FrontendController);
