// Generated by CoffeeScript 1.7.1
var Responses;

Responses = (function() {
  function Responses() {}

  Responses.prototype.SuccessJson = require('./Responses/SuccessJson').SuccessJson;

  Responses.prototype.ErrorJson = require('./Responses/ErrorJson').ErrorJson;

  Responses.prototype.NormalizedJson = require('./Responses/NormalizedJson').NormalizedJson;

  return Responses;

})();

GLOBAL.Responses = Responses;
