// Generated by CoffeeScript 1.7.1
var SerializableError;

SerializableError = (function() {
  function SerializableError() {}

  SerializableError.prototype.toJSON = function() {
    throw Error("toJSON is not implemented for child of SerializableError class");
  };

  return SerializableError;

})();

GLOBAL.SerializableError = SerializableError;
