// Generated by CoffeeScript 1.7.1
var BaseUserController,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BaseUserController = require('./user').BaseUserController;

exports.FrontendController = (function(_super) {
  var self;

  __extends(FrontendController, _super);

  self = FrontendController;

  function FrontendController() {
    FrontendController.__super__.constructor.apply(this, arguments);
  }

  FrontendController.preprocessRequest = function(req, res, next) {
    var userPromise;
    FrontendController.__super__.constructor.preprocessRequest.apply(this, arguments);
    FrontendController.getStatic('assets').js.addFile("lib/jquery-1.7.min");
    FrontendController.getStatic('assets').js.addFile("lib/jquery.jcarousel");
    FrontendController.getStatic('assets').js.addFile("lib/prettyCheckboxes");
    FrontendController.getStatic('assets').js.addFile("lib/DD_belatedPNG-min");
    FrontendController.getStatic('assets').js.addFile("lib/functions");
    FrontendController.getStatic('assets').js.addFile("lib/spin.min");
    FrontendController.getStatic('assets').js.addFile("lib/helpers");
    FrontendController.getStatic('assets').js.addFile("layout");
    FrontendController.getStatic('assets').css.addFile("style");
    FrontendController.getStatic('assets').css.addFile("prettyCheckboxes");
    userPromise = self.getStatic('userPromise');
    if (!userPromise) {
      FrontendController.getStatic('assets').js.addFile("lib/jquery.fancybox.pack");
      FrontendController.getStatic('assets').js.addFile("lib/jquery.validate.min");
      FrontendController.getStatic('assets').js.addFile("user-session");
      FrontendController.getStatic('assets').css.addFile("jquery.fancybox");
    }
    if (next != null) {
      return next();
    }
  };

  return FrontendController;

})(BaseUserController);
