// Generated by CoffeeScript 1.7.1
var FrontendController,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

FrontendController = require('./frontend').FrontendController;

exports.FrontendLoggedUserController = (function(_super) {
  __extends(FrontendLoggedUserController, _super);

  function FrontendLoggedUserController() {
    FrontendLoggedUserController.__super__.constructor.apply(this, arguments);
  }

  FrontendLoggedUserController.preprocessRequest = function(req, res, next) {
    FrontendLoggedUserController.__super__.constructor.preprocessRequest.apply(this, arguments);
    if ((this._user != null) && this._user) {

    } else {
      throw new ExceptionUserMessage('error', 'You must be logged in to access this page');
    }
  };

  return FrontendLoggedUserController;

})(FrontendController);
