// Generated by CoffeeScript 1.7.1
var CoreController, Model,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

CoreController = require('../../../core/controller.js').CoreController;

Model = require('../../../core/models').Model;

exports.BaseUserController = (function(_super) {
  var self;

  __extends(BaseUserController, _super);

  self = BaseUserController;

  function BaseUserController() {
    BaseUserController.__super__.constructor.apply(this, arguments);
  }

  BaseUserController.preprocessRequest = function(req, res, next) {
    var userId, userPromise;
    BaseUserController.__super__.constructor.preprocessRequest.apply(this, arguments);
    userId = req.session.userId;
    userPromise = false;
    if (userId) {
      userPromise = Model.instanceOf('user').getById(userId);
    }
    return self.setStatic('userPromise', userPromise);
  };

  return BaseUserController;

})(CoreController);
