// Generated by CoffeeScript 1.7.1
var CoreController,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

CoreController = require('../../../core/controller.js').CoreController;

exports.UserController = (function(_super) {
  __extends(UserController, _super);

  function UserController() {
    UserController.__super__.constructor.apply(this, arguments);
  }

  UserController.preprocessRequest = function(req, res, next) {
    var userId;
    UserController.__super__.constructor.preprocessRequest.apply(this, arguments);
    userId = req.session.userId;
    this._user = false;
    if (userId) {
      return this._user = userId;
    }
  };

  return UserController;

})(CoreController);
