// Generated by CoffeeScript 1.7.1
exports.Initializer = (function() {
  function Initializer(app) {
    var FacebookStrategy, LocalStrategy, passport;
    passport = require('passport');
    LocalStrategy = require('passport-local').Strategy;
    FacebookStrategy = require('passport-facebook').Strategy;
    app.set('passport', passport);
    app.set('localStrategy', LocalStrategy);
    app.use(passport.initialize());
    app.use(passport.session());
    passport.use(new LocalStrategy({
      usernameField: 'email',
      passwordField: 'password'
    }, function(username, password, done) {
      console.log('===============!!!!!!', username, password);
      return Model.instanceOf('user').login(username, password, function(user) {
        console.log('user', user);
        if (user) {
          return done(null, true, user);
        } else {
          return done(null, false, 'Incorrect login or password');
        }
      });
    }));
    passport.use(new FacebookStrategy({
      clientID: '429222097114916',
      clientSecret: '33be7ce13ab45683ea7ccb54eda7c644',
      callbackURL: "http://localhost:3000/api/user/facebook-callback"
    }, function(accessToken, refreshToken, profile, done) {
      var user;
      console.log("************ passport.use new FacebookStrategy", accessToken, refreshToken, profile, done);
      user = null;
      return done(null, profile);
    }));
    passport.serializeUser(function(user, done) {
      console.log('/////////////// passport.serializeUser', user);
      return done(null, user);
    });
    passport.deserializeUser(function(obj, done) {
      console.log('\\\\\\\\\\\\\\\\\\\\ passport.deserializeUser', id);
      return done(null, obj);
    });
  }

  return Initializer;

})();
