// Generated by CoffeeScript 1.7.1
var MainPageController, SessionController, apiPrefix;

MainPageController = require('./controllers/main_page').MainPageController;

SessionController = require('./controllers/session').SessionController;

apiPrefix = configs.config.apiRoot.val;

module.exports = function(app) {
  app.get("/", MainPageController.preprocessRequest, function(req, resp) {
    return (new MainPageController).index(req, resp);
  });
  app.post("/" + apiPrefix + "/session/login", SessionController.preprocessRequest, function(req, resp) {
    return (new SessionController).doLogin(req, resp);
  });
  return app.post("/" + apiPrefix + "/session/logout", SessionController.preprocessRequest, function(req, resp) {
    return (new SessionController).doLogout(req, resp);
  });
};
