// Generated by CoffeeScript 1.7.1
var MainPageController, apiPrefix;

MainPageController = require('./controllers/main_page').MainPageController;

apiPrefix = 'api';

module.exports = function(app) {
  return app.get("/", MainPageController.preprocessRequest, function(req, resp) {
    return (new MainPageController).index(req, resp);
  });
};
