// Generated by CoffeeScript 1.7.1

/*
  Requires all datatype classes from the ,/dataTypes dir
 */
var errors;

errors = require('include-all')({
  dirname: __dirname + '/dataTypes',
  filter: /(.+)\.js$/,
  excludeDirs: /^\.(git|svn)$/
});
