// Generated by CoffeeScript 1.7.1
var ExceptionUserMessage,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ExceptionUserMessage = (function(_super) {
  __extends(ExceptionUserMessage, _super);

  function ExceptionUserMessage(_name, _message) {
    this._name = _name;
    this._message = _message;
  }

  ExceptionUserMessage.prototype.getName = function() {
    return this._name;
  };

  ExceptionUserMessage.prototype.getMessage = function() {
    return this._message;
  };

  ExceptionUserMessage.prototype.toJson = function() {
    return {
      name: this._name,
      message: this._message
    };
  };

  return ExceptionUserMessage;

})(Error);

global.ExceptionUserMessage = ExceptionUserMessage;
