// Generated by CoffeeScript 1.7.1

/*
500 (Server Error) Response

Usage:
return res.serverError();
return res.serverError(err);
return res.serverError(err, view);
return res.serverError(err, redirectTo);

NOTE:
If something throws in a policy or controller, or an internal
error is encountered, Sails will call `res.serverError()`
automatically.
 */
var serverError;

module.exports = serverError = function(err, viewOrRedirect) {
  var locals, readabilify, req, res, sendJSON, viewReady;
  sendJSON = function(data) {
    if (req.options.jsonp && !req.isSocket) {
      return res.jsonp(new Responses.prototype.ErrorJson(data));
    } else {
      return res.json(new Responses.prototype.ErrorJson(data));
    }
  };
  req = this.req;
  res = this.res;
  res.status(500);
  this.req._sails.log.error("Sent 500 (\"Server Error\") response");
  if (err) {
    this.req._sails.log.error(err);
  }
  if (this.req._sails.config.environment === "production") {
    err = undefined;
  }
  if (req.wantsJSON) {
    return sendJSON(err);
  }
  locals = void 0;
  if (!err) {
    locals = {};
  } else if (typeof err !== "object") {
    locals = {
      error: err
    };
  } else {
    readabilify = function(value) {
      if (sails.util.isArray(value)) {
        return sails.util.map(value, readabilify);
      } else if (sails.util.isPlainObject(value)) {
        return sails.util.inspect(value);
      } else {
        return value;
      }
    };
    locals = {
      error: readabilify(err)
    };
  }
  if (typeof viewOrRedirect === "string") {
    if (viewOrRedirect.match(/^(\/|http:\/\/|https:\/\/)/)) {
      return res.redirect(viewOrRedirect);
    } else {
      return res.view(viewOrRedirect, locals, viewReady = function(viewErr, html) {
        if (viewErr) {
          return sendJSON(err);
        } else {
          return res.send(html);
        }
      });
    }
  } else {
    return res.view("500", locals, viewReady = function(viewErr, html) {
      if (viewErr) {
        return sendJSON(err);
      } else {
        return res.send(html);
      }
    });
  }
};
