// Generated by CoffeeScript 1.7.1

/*
isAdmin

@module      :: Policy
@description :: Simple policy to allow admin authenticated user
Assumes that your login action in one of your controllers sets `req.session.authenticated = true;`
@docs        :: http://sailsjs.org/#!documentation/policies
 */
module.exports = function(req, res, next) {
  if (req.session.userRoles.indexOf('admin') !== -1) {
    return next();
  }
  return res.unauthorized("You are not authorized to perform this request");
};
