// Generated by CoffeeScript 1.7.1
var piler, traceback;

traceback = require('traceback');

piler = require("piler");

exports.CoreController = (function() {
  var _params;

  _params = {};

  function CoreController() {
    this._assets = _params['assets'];
  }

  CoreController.preprocessRequest = function(req, res, next) {
    _params['assets'] = {
      js: piler.createJSManager(),
      css: piler.createCSSManager()
    };
    _params['assets'].js.bind(_params['app'], _params['srv']);
    return _params['assets'].css.bind(_params['app'], _params['srv']);
  };

  CoreController.prototype.set = function(inName, inVal) {
    return _params[inName] = inVal;
  };

  CoreController.prototype.get = function(inName) {
    return _params[inName];
  };

  CoreController.setStatic = function(inName, inVal) {
    return _params[inName] = inVal;
  };

  CoreController.getStatic = function(inName) {
    return _params[inName];
  };

  CoreController.prototype._getViewName = function() {
    var fileName, functionName, stack;
    stack = traceback();
    fileName = stack[1].file.replace(".js", '');
    functionName = stack[1].name.match(/[^.]*$/)[0];
    return "" + fileName + "/" + functionName;
  };

  return CoreController;

})();
