// Generated by CoffeeScript 1.7.1
global.getObjectClass = function(inObject) {
  if ((typeof inObject !== "object") || (inObject === null)) {
    return false;
  } else {
    return /(\w+)\(/.exec(inObject.constructor.toString())[1];
  }
};

global.getFunctionNameFromRef = function(inRef) {
  var funcName;
  if (typeof inRef === 'function') {
    funcName = /function ([^(]*)/.exec(inRef + "")[1];
  } else {
    funcName = false;
  }
  return funcName;
};

global.ucfirst = function(inStr) {
  var firstLetter, str;
  str = inStr + '';
  firstLetter = str.charAt(0).toUpperCase();
  return firstLetter + str.substr(1);
};

global.getSecsDiffToDate = function(inDate) {
  var millisDiff, now;
  now = new Date();
  millisDiff = inDate.getTime() - now.getTime();
  return millisDiff / 1000;
};
