// Generated by CoffeeScript 1.7.1
var configDb;

exports.Model = require('./model.js').Model;

configDb = require('../../application/configs/db.js').configDb();

configDb.dbs.forEach(function(db) {
  var modelClassName;
  modelClassName = ucfirst(db);
  return exports.Model[modelClassName] = require("./" + db + ".js")["" + modelClassName + "Model"];
});
