// Generated by CoffeeScript 1.7.1
var Model;

Model = (function() {
  function Model() {}

  Model._instances = [];

  Model.factory = function(inModelName) {
    var modelClass, modelInstance, modelName;
    if ((inModelName != null) && (inModelName !== '')) {
      modelName = ucfirst(inModelName);
      modelClass = require("../../application/models/" + inModelName + ".js");
      modelInstance = new modelClass[modelName];
    } else {
      modelInstance = null;
    }
    return modelInstance;
  };

  Model.instanceOf = function(inModelName) {
    var loadedModule, modelInstance, modelName;
    if ((inModelName != null) && (inModelName !== '')) {
      if ((typeof this._instances[inModelName] === 'undefined') || (this._instances[inModelName] === null)) {
        modelName = ucfirst(inModelName);
        loadedModule = require("../../application/models/" + inModelName + ".js");
        this._instances[inModelName] = new loadedModule[modelName];
      }
      modelInstance = this._instances[inModelName];
    } else {
      modelInstance = null;
    }
    return modelInstance;
  };

  return Model;

})();

exports.Model = Model;
