// Generated by CoffeeScript 1.7.1
var Db;

Db = (function() {
  function Db() {}

  Db.getMongoose = function() {
    return require('./mongoose.js').mongooseDb.instance().getMongoose();
  };

  return Db;

})();

exports.Db = Db;
