// Generated by CoffeeScript 1.7.1
var MongooseDb;

MongooseDb = (function() {
  var MongooseDbImplementation;

  function MongooseDb() {}

  MongooseDb._instance = null;

  MongooseDbImplementation = (function() {
    var db, mongoose;

    db = null;

    mongoose = null;

    function MongooseDbImplementation() {
      var connectionString, dbName, mongoConfig;
      mongoose = require('mongoose');
      mongoConfig = require('../../application/configs/db.js').configDb().mongo;
      if (mongoConfig != null) {
        dbName = mongoConfig.dbName;
        connectionString = 'mongodb://localhost/' + dbName;
        if (mongoConfig.port != null) {
          connectionString = ("mongodb://localhost:" + mongoConfig.port + "/") + dbName;
        }
        db = mongoose.connect(connectionString);
      } else {
        throw Error('There is no config object for mongo in application/configs/db.coffee');
      }
    }

    MongooseDbImplementation.prototype.getDb = function() {
      return db;
    };

    MongooseDbImplementation.prototype.getMongoose = function() {
      return mongoose;
    };

    return MongooseDbImplementation;

  })();

  MongooseDb.instance = function() {
    return this._instance != null ? this._instance : this._instance = new MongooseDbImplementation();
  };

  return MongooseDb;

})();

exports.mongooseDb = MongooseDb;
