// Generated by CoffeeScript 1.7.1
module.exports = {
  modelMessages: {
    "Auction": require('./Auction.js').messages
  },
  get: function(inModelName, inMessage) {
    console.log("@modelMessages", this.modelMessages);
    return this.modelMessages[inModelName][inMessage];
  }
};
