// Generated by CoffeeScript 1.7.1
module.exports = {
  modelMessages: {
    "Auction": require('./Auction.js').messages
  },
  get: function(inModelName, inMessage) {
    if (this.modelMessages[inModelName][inMessage] != null) {
      return this.modelMessages[inModelName][inMessage];
    } else {
      return inMessage;
    }
  }
};
