// Generated by CoffeeScript 1.7.1
var SuccessJson, _;

_ = require("underscore");

SuccessJson = (function() {
  function SuccessJson(data) {
    this.data = data != null ? data : {};
  }

  SuccessJson.prototype.toJSON = function() {
    return {
      data: this.data,
      messages: this.messages
    };
  };

  return SuccessJson;

})();

exports.SuccessJson = SuccessJson;
