// Generated by CoffeeScript 1.7.1
module.exports = {
  schema: true,
  attributes: {
    title: {
      type: "string"
    },
    description: {
      type: "string"
    },
    startPrice: {
      type: "int"
    },
    retailerPrice: {
      type: "int"
    },
    startsAt: {
      type: "datetime"
    },
    expiresAt: {
      type: "datetime"
    },
    images: {
      type: 'array'
    }
  }
};
