// Generated by CoffeeScript 1.7.1
var _;

_ = require("underscore");

module.exports = {
  schema: true,
  types: {
    arrayMinLen: function(arr, len) {
      return _.isArray(arr) && arr.length >= len;
    },
    arrayMaxLen: function(arr, len) {
      return (!_.isArray(arr)) || (_.isArray(arr) && arr.length <= len);
    },
    imagesValid: function(images) {
      var image, valid, _i, _len;
      valid = 0;
      for (_i = 0, _len = images.length; _i < _len; _i++) {
        image = images[_i];
        if (fs.existsSync("" + sails.config.app.tmpDir + "/" + image)) {
          valid++;
        }
      }
      if (valid === 0) {
        return false;
      } else {
        return true;
      }
    }
  },
  attributes: {
    title: {
      required: true,
      maxLength: 100
    },
    description: {
      required: true
    },
    startPrice: {
      required: true,
      type: "numeric",
      min: 0.01
    },
    retailerPrice: {
      required: true,
      type: "numeric",
      min: 0.01
    },
    startsAt: {
      required: true,
      type: "datetime"
    },
    expiresAt: {
      required: true,
      type: "datetime"
    },
    images: {
      required: true,
      type: "array",
      arrayMinLen: 1,
      arrayMaxLen: 6,
      imagesValid: true
    }
  }
};
