// Generated by CoffeeScript 1.7.1
var _;

_ = require("underscore");

module.exports = function(app) {
  return {
    config: require('./config.js').config(app),
    db: require('./db.js').configDb(app),
    getFrontendConfigs: function() {
      var configFileContent, configFileName, configFileParamContent, configFileParamName, configsStr, val;
      configsStr = "window.appConfig = {};\n";
      for (configFileName in this) {
        configFileContent = this[configFileName];
        if (!_.isFunction(this[configFileName])) {
          configsStr += 'appConfig[\'' + configFileName + '\'] = {};\n';
          for (configFileParamName in configFileContent) {
            configFileParamContent = configFileContent[configFileParamName];
            if (configFileParamContent.allowInFrontend) {
              val = configFileParamContent.val;
              if (_.isString(val)) {
                val = "'" + val + "'";
              }
              configsStr += 'appConfig[\'' + configFileName + '\'][\'' + configFileParamName + '\'] = ' + val + ";\n";
            }
          }
        }
      }
      return configsStr;
    }
  };
};
